
name: cowjacket
version: '1.0'
config-version: 2

profile: cowjacket_profile

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  cowjacket:
    # -------------------------
    # STAGING MODELS
    # -------------------------
    staging:
      +materialized: view
      +schema: "{% if target.name == 'production' %}analytics{% elif target.name == 'staging' %}dbt_ci{% else %}dbt_dev{% endif %}"

    # -------------------------
    # INTERMEDIATE MODELS
    # -------------------------
    intermediate:
      +materialized: view
      +schema: "{% if target.name == 'production' %}analytics{% elif target.name == 'staging' %}dbt_ci{% else %}dbt_dev{% endif %}"

    # -------------------------
    # MARTS MODELS
    # -------------------------
    marts:
      +materialized: table
      +schema: "{% if target.name == 'production' %}analytics_marts{% else %}dbt_dev{% endif %}"
      +enabled: "{{ target.name == 'production' }}"
