name: Launchmart_dbt
version: "1.0"
config-version: 2

profile: Launchmart_dbt

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  Launchmart_dbt:
    staging:
      +materialized: view
      +schema: "{{ target.schema }}_staging"

    intermediate:
      +materialized: view
      +schema: "{{ target.schema }}_intermediate"

    marts:
      +materialized: table
      +schema: "{{ target.schema }}_marts"
      fct_orders:
        +schema: "{{ 'Launchmart_analytics_marts' if target.name == 'production' else target.schema ~ '_marts' }}"
